apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /tms-min-side-assets/internal/isAlive
    initialDelay: 20
    timeout: 60
  readiness:
    path: /tms-min-side-assets/internal/isReady
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "400m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  gcp:
    buckets:
      - name: min-side-assets-prod
        lifecycleCondition:
          age: 7
          numNewerVersions: 2
          withState: ANY
  prometheus:
    enabled: true
    path: /tms-min-side-assets/internal/metrics
  env:
    - name: CORS_ALLOWED_DOMAIN
      value: "{{corsAllowedDomain}}"
    - name: NPM_CONFIG_CACHE
      value: /tmp
