apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://min-side-assets.intern.nav.no"
    - "https://min-side-assets.nav.no"
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    timeout: 60
  readiness:
    path: /internal/isReady
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  gcp:
    buckets:
      - name: min-side-assets-prod
        lifecycleCondition:
          age: 7
          numNewerVersions: 2
          withState: ANY
  prometheus:
    enabled: true
    path: /internal/metrics
  env:
    - name: CORS_ALLOWED_DOMAIN
      value: "{{corsAllowedDomain}}"
    - name: NPM_CONFIG_CACHE
      value: /tmp
