name: Build and deploy min-side-asset-proxy
on:
  push:
    branches:
    - main
    - react-19

jobs:
  build:
    name: "Build and push Docker-image"
    runs-on: ubuntu-latest

    permissions:
      id-token: 'write'

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'

      - name: "Install dependencies"
        run: npm ci
      - name: Run tests
        run: npm test

      - name: "Build and push"
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: min-side
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deployToDev:
    name: "Deploy to dev-gcp"
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to dev-gcp
      uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: nais/nais-dev.yml
        VARS: nais/dev-gcp.json
        VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}

  deployToProd:
    if: github.ref == 'refs/heads/main'
    name: "Deploy to prod-gcp"
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/nais-prod.yml
          VARS: nais/prod-gcp.json
          VAR: image=${{ needs.build.outputs.image }},version=${{ github.sha }}
